##############################################################
#
# Roots setup
#
##############################################################

TOOL_ROOTS := blockcounter

##############################################################
#
# Build rules
#
##############################################################

# This section contains the build rules for all binaries that have special build rules.
# See makefile.default.rules for the default build rules.

###### Special applications' build rules ######

# Build the intermediate object file for the bbl trace.
$(OBJDIR)blockcounter$(OBJ_SUFFIX): blockcounter.cpp
	$(CXX) $(TOOL_CXXFLAGS) $(COMP_OBJ)$@ $<	

# Build the tool as a dll (shared object) for ins trace.
$(OBJDIR)blockcounter$(PINTOOL_SUFFIX): $(OBJDIR)blockcounter$(OBJ_SUFFIX)
	$(LINKER) $(TOOL_LDFLAGS_NOOPT) $(LINK_EXE)$@ $< $(TOOL_LPATHS) $(TOOL_LIBS)
